[package]
name = "lab3"
version = "0.1.0"
authors = ["Paul <win10@list.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cursive = "0.10.0"
crossbeam = "0.7"
