[package]
name = "horse-server"
version = "0.1.0"
authors = ["Kolaer <overlordin777@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam = "0.7"
